### PR TITLE
fix: 2063 - replace div inside label elements

### LINKED ISSUE #2063: [BUG] div not allowed as child of label element
**Describe the bug**
This bug is related to a11y and occurs in SfRadio, SfCheckbox and others

### PR DESCRIPTION
**Pull request by aniamusial**
# Related issue

Closes #2063 

# Scope of work
- replaced divs with span for elements nested inside label tag

# Screenshots of visual changes
no visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [x] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by AdamPawlinski — DISMISSED** [review]
Looks good to me.

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue [hunk 1]
```diff
@@ -19,10 +19,10 @@
...
       <!-- @slot Custom checkmark markup -->
       <slot name="checkmark" v-bind="{ isChecked, disabled }">
-        <div
+        <span
           class="sf-radio__checkmark"
           :class="{ 'sf-radio__checkmark is-active': isChecked }"
-        ></div>
+        ></span>
       </slot>
       <div class="sf-radio__content">
```
Comment (justyna-13) [inline packages/vue/src/components/molecules/SfRadio/SfRadio.vue:27]: The label end tag is on line 45 so divs below should also be changed :)

**Review by justyna-13 — COMMENTED** [review]
NIce :) see my comment

**Review by justyna-13 — APPROVED** [review]

**Review by AdamPawlinski — APPROVED** [review]
