### PR TITLE
fix: added new code examples for customization docs

### LINKED ISSUE #2119: [BUG] Docs: change the code examples
**Describe the bug**
Change the code example with SfPagination in `css customization` section as it is not up to date and has bugs.
Screenshot from 2021-11-17 13-39-07

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by aniamusial**
# Related issue
Closes #2119 

# Scope of work
- updated docs with new, up-to-date code examples

# Screenshots of visual changes
-

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

**Review by AdamPawlinski — COMMENTED** [review]
One thing, `isDisabled` need to be removed from the description :)

**Review by justyna-13 — COMMENTED** [review]
@AdamPawlinski I have a question: is there a reason why we should remove `isDisabled`? Wasn't this issue about adding an argument to a function and changing disabled on `:disabled=isDisabled`?

File: packages/vue/src/components/molecules/SfPagination/SfPagination.vue [hunk 1]
```diff
@@ -1,7 +1,7 @@
 <template>
   <nav class="sf-pagination">
     <!-- @slot Custom markup for previous page button -->
-    <slot name="prev" v-bind="{ isDisabled: !canGoPrev, go, prev: getPrev }">
```
Comment (justyna-13) [inline packages/vue/src/components/molecules/SfPagination/SfPagination.vue:4]: Probably it should stay - may be a BC

File: packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx [hunk 2]
```diff
@@ -281,12 +281,12 @@ We can use the latest to disable buttons when they're not usable.
   :visible="5"
   @click="page => currentPage = page"
 >
-  <template #prev="{ isDisabled, go }">
-    <button @click="go()" :disabled="isDisabled ? true : false">prev</button>
-  </template>
-  <template #next="{ isDisabled, go }">
-    <button @click="go()" :disabled="isDisabled ? true : false">next</button>
```
Comment (justyna-13) [inline packages/vue/src/stories/getting-started/2. development guide/1. customization.stories.mdx:288]: if we decide not to remove isDisabled then this would be a good change in these examples: `:disabled="isDisabled `

**Review by justyna-13 — COMMENTED** [review]
Looks good :) the only issue I can see is BC because of removing isDisabled

**Review by justyna-13 — APPROVED** [review]

**Review by AdamPawlinski — APPROVED** [review]
