### PR TITLE
fix: performance optimization issues

### LINKED ISSUE #1559: Optimization issues
Because of performance issues, we need to introduce a few optimizations procedures:

- [ ] Remove unnecessary rendering of `transition` 

Examples: 
- https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/atoms/SfIcon/SfIcon.vue#L40 - this should be rendered only when you need a badge
- https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/atoms/SfIcon/SfIcon.vue#L40 - should be rendered only if `!isAddingToCart && !isAddedToCart`

- [ ] Try to avoid components that don't have to be rendered on the server-side and wrap them by using `client-only`

Example places:
- https://github.com/vuestorefront/storefront-ui/blob/develop/packages/vue/src/components/organisms/SfCarousel/SfCarousel.vue#L10 if carousel needs a js to work, do we need to render arrows or bullets on ssr?

- [ ] if the components only take the props and render something, make them functional

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue

Closes #1559

# Scope of work
SfIcon & SfProductCard: move v-if condition to render transition only wjeb necessary.

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/atoms/SfArrow/SfArrow.vue [hunk 1]
```diff
@@ -1,22 +1,36 @@
-<template>
-  <SfButton class="sf-arrow" type="button" v-bind="$attrs" v-on="$listeners">
+<template functional>
+  <component
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfArrow/SfArrow.vue:2]: why  `component` and not simply `SfButton`?

File: packages/vue/src/components/atoms/SfArrow/SfArrow.vue [hunk 2]
```diff
@@ -1,22 +1,36 @@
...
+    :style="[data.style, data.staticStyle]" 
+    type="button" 
+    v-bind="data.attrs" 
+    v-on="listeners"
+  >
     <!--@slot Use this slot to replace arrow icon-->
     <slot>
-      <SfIcon
+      <component 
+        :is="injections.components.SfIcon"
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfArrow/SfArrow.vue:13]: similarly. I don't think it's required to use `component` for functional component.

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue [hunk 3]
```diff
@@ -1,5 +1,10 @@
-<template>
-  <div class="sf-badge">
+<template functional>
+  <div
+    :class="[data.class, data.staticClass, 'sf-badge']"
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfBadge/SfBadge.vue:3]: where this `class` and `staticClass` come from?

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue [hunk 4]
```diff
@@ -1,5 +1,10 @@
...
+    :style="[data.style, data.staticStyle]"
+    v-bind="data.attrs"
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfBadge/SfBadge.vue:5]: once we use `v-bind`, I don't think we need to specific `style = data.style`. Can you verify?

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue [hunk 5]
```diff
@@ -1,5 +1,10 @@
...
+    v-on="listeners"
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfBadge/SfBadge.vue:6]: $listeners or listeners?

File: packages/vue/src/components/atoms/SfArrow/SfArrow.vue (hunk 1 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfArrow/SfArrow.vue:2]: Because it's functional component and I cannot register custom component normally and I didn't want to use render function. That is why I used this workaround. I found it in this article https://dev.to/vhoyer/functional-components-in-vue-js-20fl

File: packages/vue/src/components/atoms/SfArrow/SfArrow.vue (hunk 2 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfArrow/SfArrow.vue:13]: It's the same like above.

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue (hunk 3 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfBadge/SfBadge.vue:3]: I added this data.class and data.staticClass to make this functional component fully transparent. Maybe it's not needed here? I just thought it would be better for DX.

File: packages/vue/src/components/atoms/SfArrow/SfArrow.vue (hunk 1 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfArrow/SfArrow.vue:2]: @mayashavin  Wdyt? Maybe I overlooked something and it can be done in easier way?

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue (hunk 4 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfBadge/SfBadge.vue:5]: Unfortunately class and style attributes are not a part of data.attrs in functional components so I need to add them separately.

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue (hunk 5 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfBadge/SfBadge.vue:6]: In this case it should be listeners without $ :) https://vuejs.org/v2/guide/render-function.html#Passing-Attributes-and-Events-to-Child-Elements-Components

File: packages/vue/src/components/atoms/SfChevron/SfChevron.vue [hunk 6]
```diff
@@ -1,9 +1,28 @@
...
+    v-bind="data.attrs"
+    v-on="listeners"
+  >
     <!-- @slot Custom chevron markup -->
     <slot>
-      <span class="sf-chevron__bar sf-chevron__bar--left"></span>
-      <span class="sf-chevron__bar sf-chevron__bar--right"></span>
+      <span
+        :class="[
+          data.class,
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfChevron/SfChevron.vue:12]: If you add like this, it means the children will have the same class with the wrappers? For example if I use
<sf-chevron class="myclass"></sf-chevron>
it will render
<div class="myclass sf-chevron">
<span class="myclass sf-chevron__bar sf-chevron__bar--left"></span>
<span class="myclass sf-chevron__bar sf-chevron__bar--right"></span>
</div>

I don't think this is the correct behavior. Plus I think by default classes are already inherited to the main wrapper. Why do we need to specify?

File: packages/vue/src/components/atoms/SfIcon/SfIcon.vue [hunk 7]
```diff
@@ -29,6 +29,13 @@
         />
       </svg>
     </slot>
+    <slot name="badge" v-bind="{ badgeLabel, hasBadge }">
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfIcon/SfIcon.vue:32]: please remove this. We already concluded that we have this removed from `SfIcon` since it's not the correct behavior of an Atom component.

File: packages/vue/src/components/atoms/SfLoader/SfLoader.vue [hunk 8]
```diff
@@ -1,9 +1,15 @@
...
+    :style="[data.style, data.staticStyle]"
+    v-bind="data.attrs"
+    v-on="listeners"
+  >
     <transition name="sf-fade" mode="out-in">
       <!--@slot Slot for the actual content being loaded -->
-      <slot v-if="!loading"></slot>
-      <div v-else class="sf-loader__overlay">
+      <slot v-if="!props.loading"></slot>
+      <div v-else :class="[data.class, data.staticClass, 'sf-loader__overlay']">
```
Comment (mayashavin) [inline packages/vue/src/components/atoms/SfLoader/SfLoader.vue:12]: Same problem with class inheritance

**Review by mayashavin — CHANGES_REQUESTED** [review]
see my comments :)

File: packages/vue/src/components/atoms/SfChevron/SfChevron.vue (hunk 6 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfChevron/SfChevron.vue:12]: You are right it should be there I remove them. Thank you :)

File: packages/vue/src/components/atoms/SfBadge/SfBadge.vue (hunk 5 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfBadge/SfBadge.vue:6]: Should I leave it like it is now?

File: packages/vue/src/components/atoms/SfIcon/SfIcon.vue (hunk 7 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfIcon/SfIcon.vue:32]: Yes of course I forgot to remove it after changes, sorry.

File: packages/vue/src/components/atoms/SfLoader/SfLoader.vue (hunk 8 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfLoader/SfLoader.vue:12]: Also changed.

Comment (AdamPawlinski) [reply packages/vue/src/components/atoms/SfLoader/SfLoader.vue:12]: I removed nested classes like this also from other components. Is that alright?

Comment (mayashavin) [reply packages/vue/src/components/atoms/SfLoader/SfLoader.vue:12]: yes @AdamPawlinski :)

**Comment by AdamPawlinski** [comment]
I added also info to releases and migration guide, but tell me if it is not necessary, I'll remove it then.

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx [hunk 9]
```diff
@@ -344,17 +344,12 @@ Please refer to the below table for the deprecated variables and their alternati
       <div>N/A</div>
     </div>
   </div>
-</div>
-
-And the followings are planned be deprecated soon (from v0.11.0 onwards)
-
+</div>SfImage`
```
Comment (mayashavin) [inline packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx:347]: Remove SfImage text here :)

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx [hunk 10]
```diff
@@ -344,17 +344,12 @@ Please refer to the below table for the deprecated variables and their alternati
       <div>N/A</div>
     </div>
   </div>
-</div>
-
```
Comment (mayashavin) [inline packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx:348]: why remove these lines?

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx [hunk 11]
```diff
@@ -394,4 +389,33 @@ It was replaced by grid styling set directly in the inline CSS like this:
...
+- [SfProperty](?path=/story/components-atoms-property--common)
+- [SfTextarea](?path=/story/components-atoms-textarea--common)
+
+So the example component is now looking like this:
+
+```
+<template functional>
+  <div
+    :class="[data.class, data.staticClass, 'sf-badge']"
+    :style="[data.style, data.staticStyle]"
```
Comment (mayashavin) [inline packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx:415]: remove `data.class` and `data.staticClass` from this example.

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx [hunk 12]
```diff
@@ -394,4 +389,33 @@ It was replaced by grid styling set directly in the inline CSS like this:
       <slot />
     </div>
   </footer>
-```
\ No newline at end of file
+```
+
+## Atoms refactored
+
+As the better web performance is one of our main goals, we refactored components without additional logic into functional components.
```
Comment (mayashavin) [inline packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx:396]: "As the better web performance is one of our main goals, the following components have been changed into functional components."

Remove "This is the list of changed components:" :)

**Review by mayashavin — COMMENTED** [review]
Great job! Just minor changes required :)

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx (hunk 12 above)
Comment (AdamPawlinski) [reply packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx]: Ok fixed :)

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx (hunk 11 above)
Comment (AdamPawlinski) [reply packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx:417]: removed

File: packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx (hunk 10 above)
Comment (AdamPawlinski) [reply packages/vue/src/stories/releases/v0.10.0/migration.stories.mdx]: my mistake.

**Review by mayashavin — DISMISSED** [review]

**Review by mayashavin — APPROVED** [review]
