### PR TITLE
fix: Image elements do not have explicit width and height

### LINKED ISSUE #1831: [BUG] Image elements do not have explicit width and height
**Describe the bug**

image

**How to reproduce**

**Expected behavior**

**Actual behavior**
What actual happened.

**Code examples**
Sample code (or your configuration) to help us reproduce the bug faster or to understand your use case.
```
//Write code here
```
Or add code snippets (Code sandbox)

**Screenshots**

**Devices (please complete the following information):**
 - Device: [e.g. iPhone6, Desktop]
 - Browser: [e.g chrome, safari][version]

**Additional context**
Anything you would like to add but was not sure which section it fits. For example: tech stack used (Nuxt, Vue, Gridsome, React, etc)

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue

Closes #1831

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/organisms/SfHeader/SfHeader.vue [hunk 1]
```diff
@@ -9,6 +9,8 @@
               v-if="logo"
               :src="logo"
               :alt="title"
+              :width="34"
```
Comment (Baroshem) [inline packages/vue/src/components/organisms/SfHeader/SfHeader.vue:12]: This indeed solves the problem but maybe it would be a good opportunity to introduce two new props to SfHeader? In this component we accept a prop of logo that is being passed to the SfImage component. So instead of hardcoding the sizes like that we can create props with default values so that when user passes their own props the size of logo would be changed without using CSS.

```vue
props: {
  logoHeight: {
   type: Number,
   default: 35
  } ...
}
```

And then here

```suggestion
              :width="logoWidth"
              :height="logoHeight"
```

**Review by Baroshem — CHANGES_REQUESTED** [review]
Your solution solves the problem but we can make this more customizable to increase DX

**Review by Baroshem — APPROVED** [review]
Awesome!
