### PR TITLE
fix: change event in radio component

### LINKED ISSUE #1604: [BUG] SfRadio - bug in older browsers
**Describe the bug**
A lot of older browsers don’t support input events on radio buttons.

https://caniuse.com/input-event - note 4

Probably should be changed to a change event

### PR DESCRIPTION
**Pull request by AdamPawlinski**
# Related issue

Closes #1604 

# Scope of work
Add change event emitted from SfRadio component.

# Screenshots of visual changes

# Checklist

- [x] No commented blocks of code left
- [x] Run tests and docs
- [x] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [] I followed [composition rules](https://docs.storefrontui.io/contributing/coding-guidelines.html#component-rules) for my component
- [] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue [hunk 1]
```diff
@@ -93,6 +93,7 @@ export default {
   methods: {
     inputHandler() {
       this.$emit("input", this.value);
+      this.$emit("change", this.value);
```
Comment (mayashavin) [inline packages/vue/src/components/molecules/SfRadio/SfRadio.vue:96]: why do we want two events to be emitted at the same time? If it is about the input event not supported, then this is not the right place to add the emitter. This `inputHandler` is tied to a specific event listener of the radio button `@input="inputHandler"` which is the reported problem. It should be `@change="changeHandler`

**Review by mayashavin — CHANGES_REQUESTED** [review]
See my comments

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue (hunk 1 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.vue:95]: Yes, you're right, I changed that.

File: packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js [hunk 2]
```diff
@@ -99,7 +102,7 @@ const Template = (args, { argTypes }) => ({
   :disabled="disabled"
   :required="required"
   v-model="selected"
-  @input="input"
+  @change="change"
```
Comment (mayashavin) [inline packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js:105]: why not leave both event?

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue [hunk 3]
```diff
@@ -91,8 +91,8 @@ export default {
     },
   },
   methods: {
-    inputHandler() {
-      this.$emit("input", this.value);
+    changeHandler() {
+      this.$emit("change", this.value);
```
Comment (mayashavin) [inline packages/vue/src/components/molecules/SfRadio/SfRadio.vue:95]: If you change it like this, it will cause migration problem. Why not keep `input` emitter event and only do assign it to the `@change` native event?

**Review by mayashavin — CHANGES_REQUESTED** [review]
See my comments :)

File: packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js (hunk 2 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.stories.js:109]: I didn't understand what you suggested before. So now it should good I think.

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue (hunk 3 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.vue:95]: Please see my changes.

**Comment by tikolakin** [comment]
Hi there, thank for the fix. Do you think it will be possible to get it in the next release?
We still have plenty of users with older browser who experience the bug.
Thanks

**Comment by AdamPawlinski** [comment]
According to our milestones It will be released in 0.11.0 version. Currently we are working on hotfix which has higher priority.

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue (hunk 3 above)
Comment (mayashavin) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.vue:95]: @AdamPawlinski I meant we should keep both `inputHandler` and `changeHandler` since both are tied to two different types of events, then in template we should do
`@input="inputHandler" @change="changeHandler"`

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue [hunk 4]
```diff
@@ -14,7 +14,7 @@
         :value="value"
         :checked="isChecked"
         :disabled="disabled"
-        @input="inputHandler"
+        @change="changeHandler"
```
Comment (mayashavin) [inline packages/vue/src/components/molecules/SfRadio/SfRadio.vue:17]:
```
@change="changeHandler"
@input="inputHandler"
```

**Review by mayashavin — CHANGES_REQUESTED** [review]

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue (hunk 4 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.vue:17]: Ok I finally changed it :) Sorry for misunderstanding.

**Review by mayashavin — APPROVED** [review]

File: packages/vue/src/components/molecules/SfRadio/SfRadio.vue (hunk 4 above)
Comment (AdamPawlinski) [reply packages/vue/src/components/molecules/SfRadio/SfRadio.vue:17]: > Hi there, thank for the fix. Do you think it will be possible to get it in the next release?
> We still have plenty of users with older browser who experience the bug.
> Thanks

@mayashavin can we include it in earlier release as it is important for older browsers users?
