### PR TITLE
fix: SfHeader - links inside SfHeaderNavigationItem 

### LINKED ISSUE #2124: [BUG] SfHeader - SfLink inside SfHeaderNavigationItem
**Describe the bug**
There is a wrong implementation in SfHeader in default.vue. SfHeaderNavigationItem has SfLink inside and this causes there are duplicated a tags.

**How to reproduce**
1. Go to default view or Home page
2. See HTML of SfHeader
3. See duplicated liks

**Expected behavior**
No duplicated links

### PR DESCRIPTION
**Pull request by justyna-13**
# Related issue

Closes #2124

# Scope of work

# Screenshots of visual changes

# Checklist

- [ ] No commented blocks of code left
- [ ] Run tests and docs
- [ ] Self code-reviewed
- [ ] Changes documented 

If applicable:

- [ ] I followed [composition rules](https://docs.storefrontui.io/?path=/story/introduction-contributing-guide-code-guidelines--page) for my component
- [ ] I tested the component in most common device sizes (can be tested in Storybook [from viewport addon in top menu](https://github.com/storybooks/storybook/tree/master/addons/viewport))

### CODE REVIEW

File: packages/nuxt/layouts/default.vue [hunk 1]
```diff
@@ -20,9 +20,10 @@
       <template #navigation>
         <SfHeaderNavigationItem
             v-for="(item, i) in navigation"
-            :key="i">
-          <SfLink :link="item.link">{{item.name}}</SfLink>
-        </SfHeaderNavigationItem>
+            :key="i"
```
Comment (aniamusial) [inline packages/nuxt/layouts/default.vue:23]: suggestion: I know this is a copy-paste, but I think using only index as key is not really descriptive and can cause updates issue, maybe we should change it to something like: ```sf-header-navigation-item-${i}```? WDYT?

**Review by aniamusial — APPROVED** [review]

**Review by AdamPawlinski — APPROVED** [review]
