### PR TITLE
fix: cjs support

### LINKED ISSUE #2699: [Bug]: Error [ERR_REQUIRE_ESM]: require() of ES Module ...... not supported.
### Describe the Bug

I'm using storefront-ui with Remix.run. But when I upgrade to `2.2.0` it shows me below errors

### Current behavior

_No response_

### Expected behavior

It should work.

### Steps to reproduce

_No response_

### What package and version of StorefrontUI are you using?

@storefront-ui/react@2.2.0

### What framework does your application use?

React, Remix

### What version of Node.js are you using?

v19.8.1

### What browser (and version) are you using?

Chrome

### What operating system (and version) are you using?

macOS

### Relevant log output

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/zoloo/code/ecomm/storefront/node_modules/react-merge-refs/dist/index.mjs not supported.
Instead change the require of /Users/zoloo/code/ecomm/storefront/node_modules/react-merge-refs/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Module.<anonymous> (/Users/zoloo/code/ecomm/storefront/node_modules/@storefront-ui/react/dist/hooks/useScrollable/useScrollable.cjs.js:1:108)
    at Module.<anonymous> (/Users/zoloo/code/ecomm/storefront/node_modules/@storefront-ui/react/dist/index.cjs.js:1:5663)
    at Object.<anonymous> (/Users/zoloo/code/ecomm/storefront/build/index.js:1028:21)
    at /Users/zoloo/code/ecomm/storefront/node_modules/@remix-run/serve/dist/index.js:43:17
    at Layer.handle [as handle_request] (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:144:13)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:140:7)
    at Route.dispatch (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/layer.js:95:5)
    at /Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:284:15
    at param (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:365:14)
    at param (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:376:14)
    at Function.process_params (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:421:3)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:280:10)
    at logger (/Users/zoloo/code/ecomm/storefront/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:328:13)
    at /Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/express/lib/router/index.js:280:10)
    at SendStream.error (/Users/zoloo/code/ecomm/storefront/node_modules/serve-static/index.js:121:7)
    at SendStream.emit (node:events:512:28)
    at SendStream.error (/Users/zoloo/code/ecomm/storefront/node_modules/send/index.js:270:17)
    at SendStream.onStatError (/Users/zoloo/code/ecomm/storefront/node_modules/send/index.js:417:12)
    at next (/Users/zoloo/code/ecomm/storefront/node_modules/send/index.js:759:28)
    at /Users/zoloo/code/ecomm/storefront/node_modules/send/index.js:767:23
    at FSReqCallback.oncomplete (node:fs:195:21)
```

### Able to fix / change the documentation?

- [ ] Yes
- [X] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by dkacper**
# Related issue

Closes #2699

# Scope of work

One of the packages `react-merge-refs` does not support CJS. It provides one function so I moved it to our utils.

I was able to reproduce the issue. Then I set up a Remix project and linked the SFUI package locally and it works.

# Screenshots of visual changes

# Checklist

- [x] Self code-reviewed
- [x] Changes documented
- [x] Semantic HTML
- [x] SSR-friendly
- [x] Caching friendly
- [x] a11y for WCAG 2.0 AA
- [x] examples created
- [x] blocks created
- [ ] cypress tests created

### CODE REVIEW

File: packages/sfui/frameworks/react/shared/utils/refs.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+  return (value) => {
+    refs.forEach((ref) => {
+      if (typeof ref === 'function') {
+        ref(value);
+      } else if (ref != null) {
+        (ref as React.MutableRefObject<T | null>).current = value;
+      }
+    });
+  };
+}
```
Comment (FRSgit) [inline packages/sfui/frameworks/react/shared/utils/refs.ts:13]: Looks a bit too loosely-typed. I see that `LegacyRef` might be a string - shouldn't we cover this case? Also doing `ref != null` is effectively the same as `!ref`, isn't it?

Comment (dkacper) [reply packages/sfui/frameworks/react/shared/utils/refs.ts:13]: This is literally the same [code](https://github.com/gregberge/react-merge-refs/blob/main/src/index.tsx) form the lib we've been using for a while. I don't want to change it.

And no `ref != null` returns `true` if ref is anything but null or undefined (because `null == undefined` is true), while `!ref` returns `true` for all falsy values, means for null and undefined in particular. It also doesn't return true for truthy values.
https://dorey.github.io/JavaScript-Equality-Table/

**Review by FRSgit — APPROVED** [review]

**Review by Szymon-dziewonski — APPROVED** [review]

**Comment by Szymon-dziewonski** [comment]
@dkacper once small thing, can you please check build `@storefront-ui/react` package on remix.run with option `  serverModuleFormat: "cjs",` so we would determine if this is only issue or there are more to support esm?

**Comment by dkacper** [comment]
> @dkacper once small thing, can you please check build `@storefront-ui/react` package on remix.run with option ` serverModuleFormat: "cjs",` so we would determine if this is only issue or there are more to support esm?

Already done 👍🏼
