### PR TITLE
fix: SfAccordion - memory leak

### LINKED ISSUE #2143: [BUG] SfAccordion is causing memory leak
**Describe the bug**
SfAccordion is causing memory leak.

**How to reproduce**
build: prod.
1. Go to vue-storefront theme localhost:3000/c/women/women-bags-handbag
2. Switch through categories bags > handbag & bags > shoulder bags
3. See the error

**Screenshots**
image (1)
image (2)

### PR DESCRIPTION
**Pull request by aniamusial**
# Related issue
Closes #2143 

# Scope of work
- removed mutating $children directly

# Screenshots of visual changes
-
# Testing instructions:
- start production env on nuxt
- switch between category and homepage
- check performance monitor

### CODE REVIEW

**Review by AdamPawlinski — COMMENTED** [review]
That's how it looks like on my local:
accordion-memory-leak

File: packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue [hunk 1]
```diff
@@ -57,31 +53,28 @@ export default {
...
   },
   methods: {
+    setAccordionItems() {
+      if (this.$children && this.$children.length) {
+        this.items.push(...this.$children);
+      }
+    },
     setAsOpen() {
       if (this.$children && this.$children.length) {
-        // TODO remove in 1.0.0 ->
```
Comment (justyna-13) [inline packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue:70]: Just a question that isn't related to memory leak - should we remove it now? There will be `0.11.4` version and here we declared that it will be removed in `1.0.0` version? :slightly_smiling_face:

**Review by justyna-13 — APPROVED** [review]
Works on my side :1st_place_medal:
Screenshot from 2021-12-08 04-46-04

File: packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue (hunk 1 above)
Comment (aniamusial) [reply packages/vue/src/components/organisms/SfAccordion/SfAccordion.vue:70]: we don't really use it already, and this todo was added almost 2 years ago, I think its safe to do it :)

**Comment by AdamPawlinski** [comment]
I checked it once more its ok now.

**Review by AdamPawlinski — APPROVED** [review]
