### PR TITLE
fix: sfselect chevron rotate

### LINKED ISSUE #2569: [Bug]: `SfSelect` reset chevron on focus out
### Describe the Bug

https://user-images.githubusercontent.com/9987732/229819688-2ee7654f-2018-4dc0-bbb5-9bb4588e258a.mov

### Current behavior

After selecting a value from the list, the chevron is not returned to its original position.

### Expected behavior

When user click to an option it should reset default icon to chevron-down

### Steps to reproduce

See video

### What package and version of StorefrontUI are you using?

@storefront-ui/vue@^2.0.0

### What framework does your application use?

Nuxt

### What version of Node.js are you using?

16

### What browser (and version) are you using?

Firefox

### What operating system (and version) are you using?

OSX

### Relevant log output

_No response_

### Able to fix / change the documentation?

- [ ] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by runyasak**
# Related issue

Closes #2569 

# Scope of work

Chevron will rotate when select is focused.
So, I implemented `chevronRotated` as a ref variable to handle `rotate-180`.
Then, I add `onClickOutside` to handle `chevronRotated`. When clicking outside of select, the chevron should rotate back.

# Screenshots of visual changes
https://user-images.githubusercontent.com/6861191/230060193-45fd4c9e-fbc2-4115-9142-fd180f16d1cc.mov

# Discussion

This problem occurs for React too. Should I update to `SfSelect.tsx` for this PR?

# Checklist

- [X] Self code-reviewed
- [ ] Changes documented
- [X] Semantic HTML
- [X] SSR-friendly
- [X] Caching friendly
- [X] a11y for WCAG 2.0 AA
- [ ] examples created
- [ ] blocks created
- [ ] cypress tests created

### CODE REVIEW

**Comment by AdamPawlinski** [comment]
@runyasak Hi, great to see your contribution here. 
I tried your solution and its much better than before, but the chevron should rotate when opening/closing dropdown and currently it doesn't work exactly like that. Would you like to try to fix it? 
And React version would be also nice to have, could you also handle it?

**Comment by runyasak** [comment]
> @runyasak Hi, great to see your contribution here. I tried your solution and its much better than before, but the chevron should rotate when opening/closing dropdown and currently it doesn't work exactly like that. Would you like to try to fix it? And React version would be also nice to have, could you also handle it?

Hi, @AdamPawlinski. Thank you for reviewing my PR.

* For opening/closing case (without choosing an option), I can't detect an event when clicking outside of options. I've been searching this case and found this [StackOverflow](https://stackoverflow.com/a/52539424) talking to this case.

> When you click the <select> HTML object the browser (more specifically older versions of Firefox) adds a back-drop to the document and listens for a click within it in order to close the <select> after you perform a click outside of it (also thought as helpful for misclick prevention)

I will search more for this case and fix it. If I'm wrong or misunderstanding, please explain to me more.
If you have some advices or suggestions, please let me know.

* For React version, I can handle it and I will submit to this PR soon.

**Comment by AdamPawlinski** [comment]
For clicking outside without choosing an option, you can try changing the `chevronRotated` value on blur event, wdyt? 
I wonder how to change the chevron rotation on the initial click because it doesn't work for me.

**Comment by runyasak** [comment]
> For clicking outside without choosing an option, you can try changing the `chevronRotated` value on blur event, wdyt? I wonder how to change the chevron rotation on the initial click because it doesn't work for me.

@AdamPawlinski  Thank you for your comments
* I tried blur event and it works with clicking outside for the usual case. So, I've updated my code by using `@blur` instead of `onClickOutside`, without using library.
* For the initial click, I've just tried again on my local with `yarn run dev`. It still works. You can see this in my video below:

https://user-images.githubusercontent.com/6861191/230259571-8b96b1c5-8fae-4cb9-8bd2-35a37fd5aa68.mov

I've just done only Vue version. I didn't do React version, I will do  soon.

If you have more comments, please let me know.

**Comment by runyasak** [comment]
> Nice PR @runyasak :) Can you please update the PR title to match conventional commits? So in your case, that would be: `fix: sfselect chevron rotate`.

Hi, @aniamusial. Thank you for your comments.
Sorry for my mistake. I will update my commit messages soon.

However, I have 2 commits. How should I update my commits:
* Squash to one commit with message `fix: sfselect chevron rotate`
* Or, update first commit to `fix: sfselect chevron rotate`. The second commit would be `fix: change to on blur`.

I'm a newbie to conventional commits, please suggest me or tell me to correct them. I really want to learn.

If you have more comments, please let me know. 😁

**Comment by AdamPawlinski** [comment]
@runyasak if there are any problems with react part let me know, I can take it :)

**Comment by runyasak** [comment]
> Probably it is connected with browser. On Chrome it doesn't work for me: select4 [ select4 ](https://user-images.githubusercontent.com/32042425/230314436-312b034d-aabc-47e1-918f-ca7716967ddb.gif) [ ](https://user-images.githubusercontent.com/32042425/230314436-312b034d-aabc-47e1-918f-ca7716967ddb.gif)
> 
> But on Firefox it works (but after selecting the option the chevron doesn't rotate back) select5 [ select5 ](https://user-images.githubusercontent.com/32042425/230314789-13a7e7b5-0c7b-4f6f-86ba-6989eec9123e.gif) [ ](https://user-images.githubusercontent.com/32042425/230314789-13a7e7b5-0c7b-4f6f-86ba-6989eec9123e.gif)
> 
> What browser do you use?
> 
> And one more thing, what about navigating with keys? Probably the `keydown` event will be also needed here.

* I'm using [Arc browser](https://arc.net/). However, I tried it on Chrome too, and it works. My Chrome version is 112.0.5615.49.
Here is my result:

https://user-images.githubusercontent.com/6861191/230626488-78136915-5858-45c0-856e-bac133f18866.mov

* About `keydown`, I agree with that and I will do it soon.
For my suggestion, should we use `keyup` to handle navigating? I think `keydown` will trigger many events when we hold a key.

> @runyasak if there are any problems with react part let me know, I can take it :)

I will do it soon. It would be finished tomorrow as I expect. If I have any problem, I will tell you asap.

By the way, thank you so much for your help and suggestions. 😁

**Comment by runyasak** [comment]
> And one more thing, what about navigating with keys? Probably the keydown event will be also needed here.

@AdamPawlinski  I've tried `keyup` as my first idea. It doesn't work as expected, I couldn't detect an event when select is open.
But I can detect an event with `keydown` and it works. Thank you for your suggestion.
Please, check out my [commit](https://github.com/vuestorefront/storefront-ui/pull/2574/commits/9c61d354c5847e6730d78a7cea93dd49d70e6648).

**Comment by runyasak** [comment]
@AdamPawlinski I've updated for React version.
Please, review my [commit](https://github.com/vuestorefront/storefront-ui/pull/2574/commits/43749710c418466d16c91d43af299c6f98568f88).

If you have any feedback or comments, please let me know.

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx [hunk 1]
```diff
@@ -14,9 +15,38 @@ export default function SfSelect(props: SfSelectProps) {
...
+  };
+
+  const clickSelect: MouseEventHandler<HTMLSelectElement> = (value) => {
+    setChevronRotated(true);
+    return onClick ? onClick(value) : undefined;
+  };
+
+  const keyDownSelect: KeyboardEventHandler<HTMLSelectElement> = (value) => {
+    if (value.code === 'Space') {
+      setChevronRotated(true);
```
Comment (AdamPawlinski) [inline packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx:44]: What do you think about such change:
```suggestion
  const keyDownSelect = (event: KeyboardEvent<HTMLSelectElement>) => {
    if (event.key === 'space') {
      setChevronRotated(true);
```

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx [hunk 2]
```diff
@@ -14,9 +15,38 @@ export default function SfSelect(props: SfSelectProps) {
...
+    }
+
+    return onKeyDown ? onKeyDown(value) : undefined;
+  };
+
   return (
     <div className={classNames('relative flex flex-col', wrapperClassName)} data-testid="select">
       <select
```
Comment (AdamPawlinski) [inline packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx:52]: Here `peer` is no longer needed, I think.

File: packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue [hunk 3]
```diff
@@ -66,7 +78,10 @@ const changedValue = (event: Event) => {
         },
       ]"
       data-testid="select-input"
+      @blur="onBlurSelect"
+      @click="onClickSelect"
       @change="changedValue"
+      @keydown="onKeydownSelect"
```
Comment (AdamPawlinski) [inline packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue:84]: What about `space` modifier? When added you could remove condition in `onKeydownSelect` handler.
```suggestion
      @keydown.space="onKeydownHandler"
```

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx [hunk 4]
```diff
@@ -33,6 +63,10 @@ export default function SfSelect(props: SfSelectProps) {
           className,
         )}
         data-testid="select-input"
+        onBlur={blurSelect}
+        onChange={changedValue}
+        onClick={clickSelect}
+        onKeyDown={keyDownSelect}
```
Comment (AdamPawlinski) [inline packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx:69]: What do you think about changing the names of handlers to `blurHandler`, `clickHandler`, `keydownHandler`?

**Review by AdamPawlinski — COMMENTED** [review]
Good job! thanks for your work, please see some small comments :)

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx (hunk 1 above)
Comment (AdamPawlinski) [reply packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx]: My bad, `event.code` is the right solution :).

**Review by AdamPawlinski — APPROVED** [review]
Looks good, thank you for your effort @runyasak :+1:

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx [hunk 5]
```diff
@@ -14,16 +15,45 @@ export default function SfSelect(props: SfSelectProps) {
...
+    return onClick ? onClick(event) : undefined;
+  };
+
+  const keydownHandler = (event: KeyboardEvent<HTMLSelectElement>) => {
+    if (event.code === 'Space') {
+      setChevronRotated(true);
+    }
+
+    return onKeyDown ? onKeyDown(event) : undefined;
+  };
```
[the remark this answers is not in the document]
Comment (runyasak) [reply packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx:48]: @dkacper
Wow. `composeHandler` would be handier to handle events with a callback function.
I would update soon. Thank you so much.

[the remark this answers is not in the document]
Comment (runyasak) [reply packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx]: https://github.com/vuestorefront/storefront-ui/pull/2574/commits/ab5b3aae660f725b9ac0c4d4101e7587d4f4663e

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx (hunk 4 above)
Comment (runyasak) [reply packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx]: https://github.com/vuestorefront/storefront-ui/pull/2574/commits/7b24a1ac2af1ba87cb4eb7fa423429edb324cce0

File: packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx (hunk 1 above)
Comment (runyasak) [reply packages/sfui/frameworks/react/components/SfSelect/SfSelect.tsx]: https://github.com/vuestorefront/storefront-ui/pull/2574/commits/38b4f08ffde4f8010d16d39146832dddefe6717a

File: packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue (hunk 3 above)
Comment (runyasak) [reply packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue]: 5b1b058aea610378984cf43effa1ab3a76cdbd54

File: packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue [hunk 6]
```diff
@@ -66,7 +78,10 @@ const changedValue = (event: Event) => {
         },
       ]"
       data-testid="select-input"
+      @blur="onBlurSelect"
```
[the remark this answers is not in the document]
Comment (runyasak) [reply packages/sfui/frameworks/vue/components/SfSelect/SfSelect.vue]: e91075a05e09fde1235f67fa5f6fe60e97127d46

**Review by dkacper — APPROVED** [review]
Thanks for your contribution @runyasak
